# Development Configuration
# Overrides base.yaml values for local development

database:
  url: "postgres://user:password@localhost:5432/myapp?sslmode=disable"

jwt:
  secret: "dev-secret-key"

rate_limit:
  requests_per_second: 100
  burst: 200
