// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns overall health status with all component checks",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "All components healthy",
                        "schema": {
                            "$ref": "#/definitions/myapp_pkg_health.Response"
                        }
                    },
                    "503": {
                        "description": "One or more components unhealthy",
                        "schema": {
                            "$ref": "#/definitions/myapp_pkg_health.Response"
                        }
                    }
                }
            }
        },
        "/health/liveness": {
            "get": {
                "description": "Indicates if the application is running and should not be restarted",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Kubernetes liveness probe",
                "responses": {
                    "200": {
                        "description": "Application is alive",
                        "schema": {
                            "$ref": "#/definitions/myapp_pkg_health.Response"
                        }
                    }
                }
            }
        },
        "/health/readiness": {
            "get": {
                "description": "Indicates if the application is ready to accept traffic",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Kubernetes readiness probe",
                "responses": {
                    "200": {
                        "description": "Application ready to accept traffic",
                        "schema": {
                            "$ref": "#/definitions/myapp_pkg_health.Response"
                        }
                    },
                    "503": {
                        "description": "Application not ready",
                        "schema": {
                            "$ref": "#/definitions/myapp_pkg_health.Response"
                        }
                    }
                }
            }
        },
        "/health/startup": {
            "get": {
                "description": "Indicates if the application has started successfully",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Kubernetes startup probe",
                "responses": {
                    "200": {
                        "description": "Application started",
                        "schema": {
                            "$ref": "#/definitions/myapp_pkg_health.Response"
                        }
                    },
                    "503": {
                        "description": "Application not started",
                        "schema": {
                            "$ref": "#/definitions/myapp_pkg_health.Response"
                        }
                    }
                }
            }
        },
        "/info": {
            "get": {
                "description": "Get aggregated information from all registered info providers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Get application information",
                "responses": {
                    "200": {
                        "description": "Aggregated information",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "myapp_pkg_health.ComponentHealth": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": true
                },
                "status": {
                    "$ref": "#/definitions/myapp_pkg_health.Status"
                }
            }
        },
        "myapp_pkg_health.Response": {
            "type": "object",
            "properties": {
                "components": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/myapp_pkg_health.ComponentHealth"
                    }
                },
                "status": {
                    "$ref": "#/definitions/myapp_pkg_health.Status"
                }
            }
        },
        "myapp_pkg_health.Status": {
            "type": "string",
            "enum": [
                "UP",
                "DOWN"
            ],
            "x-enum-varnames": [
                "StatusUp",
                "StatusDown"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Microservice API",
	Description:      "Production-ready Go microservice template with observability and best practices",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
