name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.2'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod tidy && git diff --exit-code go.mod go.sum

    - name: Install swag
      run: go install github.com/swaggo/swag/cmd/swag@latest

    - name: Generate Swagger documentation
      run: swag init -g cmd/server/main.go --output docs --parseDependency --parseInternal

    - name: Build
      run: go build -v ./cmd/server

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: myapp-binary
        path: server
