name: Copilot Setup Steps

# This workflow pre-installs tools and dependencies to speed up Copilot agent operations.
# It runs during the environment setup phase before the Copilot agent executes tasks.
# See: https://docs.github.com/en/enterprise-cloud@latest/copilot/how-tos/use-copilot-agents/coding-agent/customize-the-agent-environment

on:
  workflow_dispatch:
  
jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      # Checkout repository to access go.mod and other project files
      - name: Checkout repository
        uses: actions/checkout@v5

      # Set up Go with version matching project requirements
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.2'

      # Cache Go modules for faster subsequent runs
      # This is the most frequently used optimization across all workflows
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Pre-download Go dependencies
      # This speeds up build, test, and development operations
      - name: Download Go dependencies
        run: go mod download 

      # Install golangci-lint for code quality checks
      # Common tool for Go projects
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
          golangci-lint --version 

      # Pre-build common Go tools to cache them
      - name: Pre-build Go tools
        run: |
          go build -v ./cmd/server
          go test -v -run=^$ ./... # Compile tests without running them   

      # Verify all tools are installed correctly
      - name: Verify installations
        run: |
          echo "=== Go version ==="
          go version
          
          echo "=== Golangci-lint version ==="
          golangci-lint --version
          
          echo "=== Docker version ==="
          docker --version
          
          echo "✅ All tools installed successfully"

      # Summary of what was set up
      - name: Setup summary
        run: |
          echo "🚀 Copilot environment setup complete!"
          echo ""
          echo "The following tools and dependencies have been pre-installed:"
          echo "  ✓ Go 1.25.2 with cached modules"
          echo "  ✓ Project dependencies (go mod download)"
          echo "  ✓ golangci-lint"
          echo ""
          echo "This setup is based on the most frequently used tools in:"
          echo "  - build.yml (Go, swag, modules)"
          echo "  - test.yml (Go, modules, test tools)"
          echo "  - deploy.yml (Docker, Helm, kubectl)"
          echo "  - scripts-test.yml (Go, modules)"
