name: Windows Direct Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-windows-direct:
    name: Run Go Tests Directly on Windows
    runs-on: windows-latest
    permissions:
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.2'

    - name: Download dependencies
      run: go mod download

    - name: Run tests with verbose logging
      run: go test ./... -v -count=1
