name: Windows Direct Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-windows-direct:
    name: Run Go Tests Directly on Windows
    runs-on: windows-latest
    permissions:
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up PostgreSQL
      uses: ikalnytskyi/action-setup-postgres@v8
      with:
        username: testuser
        password: testpassword
        database: testdb
        port: 5432
      id: postgres

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.2'

    - name: Download dependencies
      run: go mod download

    - name: Run tests with verbose logging
      shell: pwsh
      run: |
        Write-Host "Running go test with verbose logging..." -ForegroundColor Cyan
        Write-Host "Test command: go test ./... -v -count=1" -ForegroundColor Yellow
        go test ./... -v -count=1
        $exitCode = $LASTEXITCODE
        Write-Host "Tests completed with exit code: $exitCode" -ForegroundColor $(if ($exitCode -eq 0) { "Green" } else { "Red" })
        exit $exitCode
      env:
        DATABASE_URL: "host=localhost user=testuser password=testpassword dbname=testdb port=5432 sslmode=disable"
        JWT_SECRET: "test-secret-key"
        SERVER_PORT: "8081"
